# Generated by Django 5.2.3 on 2025-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writeup',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='DP',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='profile_picture'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='writeup',
            name='contents',
            field=models.TextField(),
        ),
    ]
