# Generated by Django 5.2.3 on 2025-07-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_title_writeup_title_alter_userprofile_dp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
