# Generated by Django 5.2.3 on 2025-07-13 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_writeup_author_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='onwriteup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.writeup'),
        ),
    ]
